### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by vasicvuk** [Sicos1977/OfficeConverter#10]
Is there a chance to have this working on a .NET Core?

**Comment by Sicos1977** [comment]
Don't know but one this is that this will only run on Windows if you are going to use Microsoft Office

**Comment by vasicvuk** [comment]
Libreoffice should work on .net core

**Comment by Sicos1977** [comment]
Yeah I know but I also do registry things and that is bound to Windows (sorry for the late response ,,, totally missed this issue)

**Comment by Sicos1977** [comment]
If you are going to use it on Windows then it will work but not on a system like Linux

**Comment by Sicos1977** [comment]
No response ... closed
