### ISSUE TITLE
does it offer watermark

### ISSUE THREAD

**Issue by swiftinitdotcom** [Sicos1977/OfficeConverter#12]
does it offer watermark?
we need before downloading watermark pdf files
https://www.c-sharpcorner.com/UploadFile/a71939/how-to-add-watermark-on-pdf-files/

**Comment by Sicos1977** [comment]
Sorry for the late reaction but no I does not.

**Comment by Sicos1977** [comment]
But if you want to add a watermark afterwards you can use my QPdfNet project. It has an option to overlay or underlay a PDF page. So if you make a PDF with a transparent image on a page then you can use the underlay command to watermark the PDF.

https://github.com/Sicos1977/QPdfNet
