### ISSUE TITLE
With a windows service, Word file conversion error

### ISSUE THREAD

**Issue by jbourree** [Sicos1977/OfficeConverter#13]
By launching the conversion of a word document in a webservice, I have the error "The file 'doc.docx' seems to be corrupt, error: Object reference not set to an instance of an object".
Is there a special configuration for windows services? The same conversion from a console application works.

**Comment by Sicos1977** [comment]
Are you running this service under another user?

**Comment by Sicos1977** [comment]
If so then make sure you have given this user launch permissions for the different office applications with this tool --> https://docs.microsoft.com/en-us/windows/win32/com/setting-processwide-security-using-dcomcnfg

**Comment by jbourree** [comment]
The service running with the same user as the one with which word is installed.

**Comment by jbourree** [comment]
The problem is not DCOM.
The fix is to create the directories:
Windows x64: C:\Windows\SysWOW64\config\systemprofile\Desktop
Windows x86: C:\Windows\System32\config\systemprofile\Desktop

**Comment by Minhounet** [comment]
I must add that "C:\Windows\System32\config\systemprofile\Desktop" must be created through windows explorer (and not a dos command line) as there is a Windows file redirection (that costs me a lot of days..).
