### ISSUE TITLE
cli_basetypes and rest types 64bit

### ISSUE THREAD

**Issue by valentasm1** [Sicos1977/OfficeConverter#14]
Hi,

In my inhouse solution for open office i have very similar idea of converting odt to pdf. Problem occurs when i migrate solution to 64bit. I tried use your libs from x64 folder but i think there version mismatch which couse some core error in openoffice
https://github.com/Sicos1977/OfficeConverter/tree/master/OfficeConverter/CLI/x64

Question.
Where did you found these libs for x64?
I was unable to find and some forums mentioned that it dont even exist for x64.

**Comment by Sicos1977** [comment]
Hi,

I use Libre Office (another fork from Open Office) and got the dev files from here --> https://api.libreoffice.org/
