### ISSUE TITLE
Could not load file or assembly 'OpenMcdf, Version=2.2.1.12, Culture=neutral, PublicKeyToken=fdbb1629d7c00800'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by drpl-debashis-pal** [Sicos1977/OfficeConverter#19]
Could not load file or assembly 'OpenMcdf, Version=2.2.1.12, Culture=neutral, PublicKeyToken=fdbb1629d7c00800'. The system cannot find the file specified.

I already have specified the full path of both the DOCX and PDF file and the location has full access to Everyone.
````
public class Class1
{
	public static void Convert(string docFile, string pdfFile)
	{
		using (var converter = new Converter())
		{
			//converter.UseLibreOffice = false;
			converter.Convert(docFile, pdfFile);
		}
	}
}
````

**Comment by Sicos1977** [comment]
That file should be present in the bin dir of your project or somewhere in the packages folder.
