### ISSUE TITLE
getting could not open word registry

### ISSUE THREAD

**Issue by swiftinitdotcom** [Sicos1977/OfficeConverter#4]
getting could not open word registry

**Comment by Sicos1977** [comment]
You have to do some more effort to get my support... just pasting a few words without anything else is not enough for me to figure out what your problem is

**Comment by swiftinitdotcom** [comment]
Ah I think I understand the issue, yours does not work without word office 365 installed on the server right? but it works great I must say when word is there or ppt is installed.

**Comment by Sicos1977** [comment]
You are right, as the readme says on the GitHub page... Office is needed.

**Comment by swiftinitdotcom** [comment]
One one dev server its working only in vs debug mode but when deployed to iis gives access denied and on another even though there is word office 365 it gives-
System.UnauthorizedAccessException: Retrieving the COM class factory for component with CLSID {000209FF-0000-0000-C000-000000000046} failed due to the following error: 80070005 Access is denied. (0x80070005 (E_ACCESSDENIED)). at OfficeConverter.Word.StartWord() in C:\tfs\OfficeConverter\OfficeConverter\Word.cs:line 164 at OfficeConverter.Word.Convert(String inputFile, String outputFile) in C:\tfs\OfficeConverter\OfficeConverter\Word.cs:line 270 at OfficeConverter.Converter.Convert(String inputFile, String outputFile, Stream logStream) in C:\tfs\OfficeConverter\OfficeConverter\Converter.cs:line 297 at .Controllers.UploadController.ConvertToPdf(FileInfo _fileinfo, Int32 caseventid, String caseid) at Pages.Dialogs.AddEvents1Dialog.PostAdd()

**Comment by Sicos1977** [comment]
You need to give the account that is used to run the site rights to start Word. The easy way out is to run the site under local system but if you don't want that then you have to set the correct rights on all the Office folders.

**Comment by swiftinitdotcom** [comment]
Thanks trying that just now.

**Comment by Sicos1977** [comment]
You can also set rights with dcomcnfg (mmc comexp.msc /32)

![image](https://user-images.githubusercontent.com/6692947/119656095-9608e000-be2a-11eb-8baf-133ce8f02b24.png)

**Comment by Sicos1977** [comment]
Also a cave at when doing multiple conversions, you can't start Word more than 10 times.
You also need to have the printer spooler enabled when doing conversions from Excel

**Comment by swiftinitdotcom** [comment]
ok right, is there any cheaper non interop option you know? thanks for your guidance

**Comment by Sicos1977** [comment]
You can use libreoffice.

**Comment by swiftinitdotcom** [comment]
https://abdulmunim.com/how-to-convert-office-documents-to-pdf-using-open-office-in-csharp/

**Comment by Sicos1977** [comment]
I know... that is already backed into this library, you just have to set this flag to use libre office

```c#
/// <summary>
///     When set then LibreOffice is used to do the conversion instead of Microsoft Office
/// </summary>
public bool UseLibreOffice { get; set; }

```
https://github.com/Sicos1977/OfficeConverter/blob/master/OfficeConverter/LibreOffice.cs

As with everything Libre Office has also some problems, not all Word documents render the same as in Word. But if your documents are not to complex Libre Office will do the job.

**Comment by swiftinitdotcom** [comment]
Thats is awesome. I tried this but it says handle is not initialized, I downloaded and installed  libre office on server.

  converter.UseLibreOffice = true;
                        converter.Convert(_fileinfo.FullName, fileName1);

**Comment by swiftinitdotcom** [comment]
https://ask.libreoffice.org/en/question/16318/error-while-establish-connection/

**Comment by swiftinitdotcom** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=64070

**Comment by swiftinitdotcom** [comment]
https://stackoverflow.com/questions/60149429/bootstrap-libreoffice-with-net-core-throws-exception

I also installed their sdk and added reference of cli dlls.
and may be I amdoin g it wrong-
  converter.Convert(**_fileinfo.FullName**, fileName1);

**Comment by Sicos1977** [comment]
I did never test this with .net core. Can you see if it works if you put the DLL in a .net framework project? .. sorry for the late response... just morning overhere (time difference).

If it works you can make a Windows service with the DLL in it and communicate with that through SOAP,gRPC or something simular. I did this once with a project that needed Chrome but gave all kind of strange error when running it from IIS

**Comment by Sicos1977** [comment]
I just tested it from a .net core project and indeed get an handle error.

![image](https://user-images.githubusercontent.com/6692947/119776129-d87efb00-bec4-11eb-8910-bd65f830f6f2.png)

Let me run a debugger and see where it failes

**Comment by swiftinitdotcom** [comment]
you are too fast thank you!

**Comment by Sicos1977** [comment]
I downloaded the latest Libre Office SDK and used those but that gives the same error, at the moment I don't have an solution. You could try to debug the CLI dll's but these are made in C++

Or if you are on a Windows Service use the solution I suggested, make a .NET framework service and communicate with that through SOAP, gRPC or something simular.

**Comment by swiftinitdotcom** [comment]
ok thanks let me try.

**Comment by swiftinitdotcom** [comment]
I tried console app dotnet frame work but it says libre office is not installed.

**Comment by swiftinitdotcom** [comment]
I installed nuget Install-Package OfficeConverter 
and it it gives LibreOffice is not installed' in dotnet framework 4.6.2 console app but when I downloaded your test solution it works just fine with windows form so not sure what ismissing in my console app.

**Comment by swiftinitdotcom** [comment]
To reproduce please install latest libre office andinstall nuget Install-Package OfficeConverter
and it it gives LibreOffice is not installed' in dotnet framework 4.6.2 new console app

**Comment by Sicos1977** [comment]
This probably has to do with your app being 32 bits and Libre Office 64 bits or the other way around.
I just made a new nuget packages to handle these kind of things

**Comment by swiftinitdotcom** [comment]
Thank you!

**Comment by swiftinitdotcom** [comment]
You were absolutely right. It was 32 bit... Thank you very much.

**Comment by Sicos1977** [comment]
:+1:
