### ISSUE TITLE
Getting Error while deploying my code to Azure App Service

### ISSUE THREAD

**Issue by biswajitsamal59** [Sicos1977/OfficeConverter#5]
I needed to convert .DOCX, .XLS, .XLXS file to .PDF file as part of my app. It's working fine on my local machine, as I have MS office installed on my system. But When I tried to deploy this application in Azure App Service plan, then it's not working as MS office is not available. I know we can install both our app and  MS office in a VM and it will work. But is there any way we can deploy this app in Azure App Service or Containerize?

ErrorMessage: Could not read registry to check Word version.  
InnerException: Could not find registry key Word.Application\CurVer.   
StackTrace:    at OfficeConverter.Word..ctor()
   at OfficeConverter.Converter.get_Word()
   at OfficeConverter.Converter.Convert(String inputFile, String outputFile, Stream logStream)

**Comment by Sicos1977** [comment]
No you do need Microsoft Office otherwise it won't work. If you want to do it without Microsoft Office then you have to buy a third party solution.

**Comment by biswajitsamal59** [comment]
Is there any service being provided by Azure cloud to convert .dcox and .xls file to pdf? If No, Can you please provide best third party paid solution for .Net 5 or .Net Core.

**Comment by Sicos1977** [comment]
https://blog.aspose.com/2020/01/02/convert-word-doc-docx-to-pdf-in-csharp-net-core/ but it is expensive
