### ISSUE TITLE
After Updating OfficeConvert cannot complile, missing reference

### ISSUE THREAD

**Issue by jkinsel2006** [Sicos1977/OfficeConverter#8]
![image](https://user-images.githubusercontent.com/61061563/142057489-47823316-c636-489f-94fc-77c277fe59a7.png)
![image](https://user-images.githubusercontent.com/61061563/142057552-5711ed8b-fbb0-44e0-953f-f648c9f6fb03.png)

**Comment by jaxnz** [comment]
Same issue on v1.7.2

**Comment by Sicos1977** [comment]
Weird since I have no problems, on what version of .NET are you in your project?

**Comment by anthonyChaussin-d4e** [comment]
Same issue, I tested in Net5 and Net6 and both are failed, is there a différent name in the new version ?

**Comment by Sicos1977** [comment]
This seems to be an issue in msgreader that I'll try to fix this week. I used Microsoft Maui and this package is giving the problems

**Comment by Sicos1977** [comment]
Should be fixed
